//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nerdle.AutoConfig.Tests.Integration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigExamples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigExamples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nerdle.AutoConfig.Tests.Integration.ConfigExamples", typeof(ConfigExamples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;collectionsConfiguration&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///    &lt;section name=&quot;nestedCollectionsConfiguration&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///    &lt;section name=&quot;arrayConfiguration&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///  
        ///  &lt;collectionsConfiguration&gt;
        ///    &lt;primes&gt;
        ///      &lt;prime&gt;2&lt;/prime&gt;
        ///      &lt;Prime&gt;3&lt;/Prime&gt;
        ///      &lt;Prime [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MappingCollections {
            get {
                return ResourceManager.GetString("MappingCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;dictionaryConfiguration&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///    &lt;section name=&quot;complexDictionaryConfiguration&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;dictionaryConfiguration&gt;
        ///    &lt;frenchWords&gt;
        ///      &lt;word key=&quot;cat&quot; value=&quot;chat&quot; /&gt;
        ///      &lt;word key=&quot;dog&quot; value=&quot;chien&quot; /&gt;
        ///      &lt;word key=&quot;monkey&quot; value=&quot;singe&quot; /&gt;
        ///    &lt;/frenchWords&gt;
        ///  &lt;/dictiona [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MappingDictionaries {
            get {
                return ResourceManager.GetString("MappingDictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;endPointConfiguration&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///    &lt;section name=&quot;pizzaConfiguration&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;endPointConfiguration url=&quot;http://foo&quot; port=&quot;80&quot; /&gt;
        ///
        ///  &lt;pizzaConfiguration name=&quot;Vege Deluxe&quot; price=&quot;9.99&quot; size=&quot;XLarge&quot;&gt;
        ///    &lt;base&gt;Stuffed Crust&lt;/base&gt;
        ///    &lt;toppings&gt;
        ///      &lt;topping&gt;Aubergine&lt;/topping&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MappingFromAttributes {
            get {
                return ResourceManager.GetString("MappingFromAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;complexConfiguration&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;complexConfiguration foo=&quot;foo&quot; bar=&quot;bar&quot; baz=&quot;baz&quot;&gt;
        ///    &lt;someService name=&quot;MyService&quot; requestTimeout =&quot;20&quot; enabled=&quot;false&quot; /&gt;
        ///    &lt;someOtherService name=&quot;MyOtherService&quot; requestTimeout=&quot;1000&quot; enabled=&quot;true&quot;&gt;
        ///      &lt;hosts&gt;
        ///        &lt;host name=&quot;HOST-01&quot; port=&quot;1700&quot; /&gt;
        ///        &lt;host name=&quot;HOST-02&quot; port=&quot;170 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MappingNestedComplexTypes {
            get {
                return ResourceManager.GetString("MappingNestedComplexTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;simpleConfiguration&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;simpleConfiguration&gt;
        ///    &lt;myString&gt;hello&lt;/myString&gt;
        ///    &lt;myInt&gt;42&lt;/myInt&gt;
        ///    &lt;myNullable&gt;23&lt;/myNullable&gt;
        ///    &lt;myEmptyNullable&gt;&lt;/myEmptyNullable&gt;
        ///    &lt;myBool&gt;true&lt;/myBool&gt;
        ///    &lt;myDate&gt;21 July 1969&lt;/myDate&gt;
        ///  &lt;/simpleConfiguration&gt;
        ///
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string MappingSimpleExamples {
            get {
                return ResourceManager.GetString("MappingSimpleExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;foo&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///    &lt;section name=&quot;bar&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///    &lt;section name=&quot;baz&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///    &lt;section name=&quot;BAZ&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;foo&gt;
        ///    &lt;name&gt;foo&lt;/name&gt;
        ///  &lt;/foo&gt;
        ///
        ///  &lt;bar&gt;
        ///    &lt;name&gt;bar&lt;/name&gt;
        ///  &lt;/bar&gt;
        ///
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpecifyingTheSectionName {
            get {
                return ResourceManager.GetString("SpecifyingTheSectionName", resourceCulture);
            }
        }
    }
}
