//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nerdle.AutoConfig.Tests.Integration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigExamples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigExamples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nerdle.AutoConfig.Tests.Integration.ConfigExamples", typeof(ConfigExamples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;CollectionsConfiguration&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///    &lt;section name=&quot;NestedCollectionsConfiguration&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///  
        ///  &lt;CollectionsConfiguration&gt;
        ///    &lt;Primes&gt;
        ///      &lt;Prime&gt;2&lt;/Prime&gt;
        ///      &lt;Prime&gt;3&lt;/Prime&gt;
        ///      &lt;Prime&gt;5&lt;/Prime&gt;
        ///      &lt;Prime&gt;7&lt;/Prime&gt;
        ///    &lt;/Primes&gt;
        ///    &lt;Colors&gt;
        ///      &lt;Color&gt;Red&lt;/Color&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MappingCollections {
            get {
                return ResourceManager.GetString("MappingCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;MappedFromAttributes&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///    &lt;section name=&quot;MappedFromPropertiesAndAttributes&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;MappedFromAttributes Url=&quot;http://foo&quot; Port=&quot;80&quot; /&gt;
        ///
        ///  &lt;MappedFromPropertiesAndAttributes Pizza=&quot;Vege Deluxe&quot; Price=&quot;9.99&quot;&gt;
        ///    &lt;Size&gt;12inch&lt;/Size&gt;&quot;
        ///    &lt;Toppings&gt;
        ///      &lt;Topping&gt;Aubergine&lt;/Toppi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MappingFromAttributes {
            get {
                return ResourceManager.GetString("MappingFromAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;NestedTypesConfiguration&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;NestedTypesConfiguration&gt;
        ///      &lt;SomeService name=&quot;MyService&quot; RequestTimeout=&quot;1000&quot; Enabled=&quot;true&quot; /&gt;
        ///      &lt;Hosts&gt;
        ///        &lt;Host name=&quot;HOST-01&quot; Port=&quot;1700&quot; /&gt;
        ///        &lt;Host name=&quot;HOST-02&quot; Port=&quot;1700&quot; /&gt;
        ///        &lt;Host name=&quot;HOST-03&quot; Port=&quot;1700&quot; /&gt;
        ///      &lt;/Hosts&gt;
        ///  &lt;/NestedTypesConfiguration&gt;
        ///
        ///&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MappingNestedComplexTypes {
            get {
                return ResourceManager.GetString("MappingNestedComplexTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;SimpleConfiguration&quot; type=&quot;Nerdle.AutoConfig.Section, Nerdle.AutoConfig&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;SimpleConfiguration&gt;
        ///    &lt;MyString&gt;hello&lt;/MyString&gt;
        ///    &lt;MyInt&gt;42&lt;/MyInt&gt;
        ///    &lt;MyNullable&gt;23&lt;/MyNullable&gt;
        ///    &lt;MyEmptyNullable&gt;&lt;/MyEmptyNullable&gt;
        ///    &lt;MyBool&gt;true&lt;/MyBool&gt;
        ///    &lt;MyDate&gt;21 July 1969&lt;/MyDate&gt;
        ///  &lt;/SimpleConfiguration&gt;
        ///
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string MappingSimpleExamples {
            get {
                return ResourceManager.GetString("MappingSimpleExamples", resourceCulture);
            }
        }
    }
}
